### ISSUE TITLE
As a normal user, I want to be able to upvote or downvote an answer of a question so that I tell others if that answer is useful or not. Sub-story of #20

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#8]
As an User of the website, I want to be able to upvote or downvote an answer of a question, so that I tell other if that answer is useful for me or not.
Related to epic story #20 

Story Points: 1
Risk: low value, low risk
Priority: low

**Comment by DrakeHunterK7** [comment]
Tasks needed to be done to complete this User Story:

- [x] Setup Database and Backend #41 

- [ ] Complete Question Template page layout #61 

- [ ] Complete question page functionality with database and backend (make it actually display answers to questions loaded from database) #62

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Log in and go to the All Questions page
2) Click on any question that already as one or more answers.
3) Upvote one of the answers.
4) Refresh the page. If your upvote is still counted and visible, then move on to next step. 
5) Downvote one of the answers.
6) Refresh the page. If Step 4 was successful, and your downvote is still counted and visible, then this feature is complete and is therefore marked closed and complete.

**Comment by DrakeHunterK7** [comment]
This feature has passed the acceptance test as of Sprint 4, hence this user story is now closed.
