### ISSUE TITLE
As a normal user, I want to be able to ask a question, so that others can help me solve my problem. Sub-story of epic story #19

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#9]
As an User of the website, I want to be able to ask a question, so that others can help me solve my problem.
Related to epic story #19 

Story Points: 3

**Comment by DrakeHunterK7** [comment]
Tasks needed to be done to complete this User Story:

- [x] Setup Database and Backend #41 

- [ ] Complete Question Template page layout #50  

- [ ] Complete question page functionality with database and backend (make it actually display answers to questions loaded from database) #51

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are completed in order and result in success, this story is therefore marked complete.

1) Log in
2) Go to Post Question page under Home 
3) Type in Question Title
4) Type in Question Text
5) Click on "Submit"
6) Go to All Questions page
7) If your new question appears at the top of the question list in the All Questions Page, then you have successfully posted a question.

**Comment by DrakeHunterK7** [comment]
This story is now closed and complete as it meets the acceptance testing criteria as set out above. Users can now successfully post a question and have their question appear in the All Questions page
